# Site settings
title: BunToy
SEOTitle: BunToy Studio | Blog
header-img: img/home.jpg
email: danielxia082@gmail.com
description: "关于Buntoy.程序与设计 | 松下百合子，Web & Mobile Lover，Software Engineer，UX Designer | 这里是松下百合子个人博客，与你一起发现更大的世界。"
keyword: "Daniel,松下百合子,小小蓝莓,小小蓝莓的博客, BunToy Blog,BunToy Wallet, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计,Android"


# Secondary Parameters
url: "https://buntoy.com"              # your host, for absolute URL
baseurl: ""                            # for example, '/blog' if your blog hosted on 'host/blog'
headercolor: "#FFFFFF"
#logo: img/logo/Project-Pages-New-Logo-Inverted.png



# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     松下百合子
zhihu_username:     松下百合子
github_username:    松下百合子
twitter_username:   松下百合子
#facebook_username:  松下百合子
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
#jekyll（读杰克尔）
plugins: [jekyll-paginate]   



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: xiabing

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
#baidu-analysis:f66b9ac164a152d61b378211a419177b

# Google Analytics
ga_track_id: 'UA-134826625-1'            # Format: UA-xxxxxx-xx
ga_domain: auto
#google-analysis:YtetPDGd1WFc9OLkb9kRFtjvw8Sl21jVJu51i13z6FQ


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "松下百合子<br>欢迎你的到来"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "BunToy CSDN",
        href: "https://blog.csdn.net/xiabing082"
    },{
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke 的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "David's Game",
        href: "https://www.ruoyaowu.com/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "170MV",
        href: "http://www.170mv.com/"
    },{
        title: "PicArt",
        href: "https://picsart.com/explore?hl=zh"
    }
]
